version: "3.5"
services:

  influxdb:
    image: influxdb:latest
    ports:
  #    - "8083:8083"
      - "8086:8086"
    env_file:
      - .secret
    environment:
      - INFLUXDB_DB=atmo
      - INFLUXDB_USER=atmo
    volumes:
      - influx-data:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - .secret
    user: "0"
    links:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mqtt:/mosquitto/config
      - mqtt-log:/mosquitto/log
      - mqtt-data:/mosquitto/data

  atmo-bridge:
    build: ./bridge
    env_file:
      - .secret
    environment:
      - BRIDGE_INFLUXDB_ADDRESS=influxdb
      - BRIDGE_INFLUXDB_DATABASE=atmo
      - BRIDGE_INFLUXDB_USER=atmo
      - BRIDGE_MQTT_USER=atmo
      - BRIDGE_MQTT_ADDRESS=mqtt
    restart: unless-stopped
    links:
      - influxdb
      - mqtt

volumes:
  influx-data:
  grafana-data:
  mqtt-data:
  mqtt-log:
